### ISSUE TITLE
Manifest: Line: 1, column: 1, Syntax error.

### ISSUE THREAD

**Issue by mapsic** [moshe/elasticsearch-comrade#163]
#### Hi
I am running with docker, here is my command to start the docker container.
``` bash
docker run -d --name elasticsearch-comrade -v $PWD/clusters/:/app/clusters/ -p 8000:8000 mosheza/elasticsearch-comrade:master
```
But it does not display the page correctly.
Error in Chrome Console: 
```
Manifest: Line: 1, column: 1, Syntax error.
```
Please help me, thank you.

**Comment by moshe** [comment]
Hey @mapsic 👋
It was a bug in the build procedure, fixed in https://github.com/moshe/elasticsearch-comrade/releases/tag/v1.0.2 you can pull the latest image `docker pull mosheza/elasticsearch-comrade:master` and try again with the same command as before 🙂

**Comment by mapsic** [comment]
Hey @moshe Thank you very much!
