### ISSUE TITLE
Sparkline graphs are incorrectly sized in Firefox

### ISSUE THREAD

**Issue by jgough** [moshe/elasticsearch-comrade#256]
If using Firefox, the sparkline graphs grow and shrink in size.  In Chrome they display a static size.
Tested in Firefox 68.2.0esr
Screenshot:
![image](https://user-images.githubusercontent.com/968442/70698073-a2dd5680-1cbe-11ea-987d-a5075be7cc63.png)

**Comment by moshe** [comment]
Thank you @jgough 
I will take a look at it soon🙂

**Comment by moshe** [comment]
reproduced and fixed🙂
Will be added to the next release
![image](https://user-images.githubusercontent.com/7490448/71545017-bd861f80-298e-11ea-9997-8e552912739c.png)
