### ISSUE TITLE
bug(server) Task "cancle" instead of "cancel"

### ISSUE THREAD

**Issue by efim-a-efim** [moshe/elasticsearch-comrade#297]
When trying to cancel task from Tasks screen, a request is made to `http://comrade-host/api/v1/task/cancle` which is wrong endpoint (correct is `cancel`). As a result, REST error occurs and task cannot be cancelled.

**Comment by moshe** [comment]
Fixed! https://github.com/moshe/elasticsearch-comrade/releases/tag/v1.1.3
