### ISSUE TITLE
Strange disk usage statistics

### ISSUE THREAD

**Issue by botzill** [moshe/elasticsearch-comrade#333]
Hi.

First of all great project you have! Really useful.

I play with it and I see this stats for each node:

<img width="205" alt="Screen Shot 2020-01-25 at 20 14 27" src="https://user-images.githubusercontent.com/4686040/73125430-7e5be600-3faf-11ea-802a-e2cfb450c7fe.png">

I see `disk(94%)` and same for other nodes.

doing a call to `/_cat/allocation?v&pretty` I get:

```
shards disk.indices disk.used disk.avail disk.total disk.percent host         ip           node
     7        7.3gb     9.9gb       39gb     48.9gb           20 10.244.5.114 10.244.5.114 elasticsearch-master-0
     7       11.7mb     2.5gb     46.3gb     48.9gb            5 10.244.3.205 10.244.3.205 elasticsearch-master-1
     8        7.3gb     9.9gb     38.9gb     48.9gb           20 10.244.0.246 10.244.0.246 elasticsearch-master-2
```

Seems that disk is actually the fee disc, not used, right?

using latest version from dockerhub.

Thx!

**Comment by dstephens1980** [comment]
I too am seeing this issue.  Using latest Comrade manual setup on Centos 7, no docker.

Have a 3 node cluster:
01d - Elasticsearch Master/Http
02d - Elasticsearch Master/Data
03d - Elasticsearch Master/Data

Comrade Disk usage:
![image](https://user-images.githubusercontent.com/37511643/73200122-cbe56980-40fb-11ea-9685-4692a76d65d2.png)

OS Disk usage for Data nodes:
![image](https://user-images.githubusercontent.com/37511643/73200318-27175c00-40fc-11ea-85f0-952453e06191.png)
