### ISSUE TITLE
attempted relative import beyond top-level package

### ISSUE THREAD

**Issue by spursy** [moshe/elasticsearch-comrade#454]
when process  pipenv run python3 index.py, I encounter the follow issue

pipenv run python3 index.py

Traceback (most recent call last):
  File "index.py", line 13, in <module>
    from .blueprints.alias import alias_bp
ModuleNotFoundError: No module named '__main__.blueprints'; '__main__' is not a package

**Comment by moshe** [comment]
Just fixed the documentation, please pull from master and follow the instructions here -> https://moshe-1.gitbook.io/comrade/installation/from-source
