### ISSUE TITLE
No such file or directory: ./static/index.html

### ISSUE THREAD

**Issue by joej** [moshe/elasticsearch-comrade#490]
templates missing?

- git clone
- cd client: npm install
- cd ../server: fix path issues so index.py can run (..connections, .blueprints) so the pieces load correctly); then start: python3 ./index.py

**shell output**
[2020-05-25 17:47:01 -0400] [89140] [ERROR] [Errno 2] No such file or directory: './static/index.html'
Traceback (most recent call last):
  File "/Users/joe/.pyenv/versions/3.7.2/lib/python3.7/site-packages/sanic/app.py", line 973, in handle_request
    response = await response
  File "./index.py", line 41, in redirect_init
    return await file(f'{current_dir}/static/index.html')
  File "/Users/joe/.pyenv/versions/3.7.2/lib/python3.7/site-packages/sanic/response.py", line 296, in file
    async with await open_async(location, mode="rb") as f:
  File "/Users/joe/.pyenv/versions/3.7.2/lib/python3.7/site-packages/aiofiles/base.py", line 75, in __aenter__
    self._obj = await self._coro
  File "/Users/joe/.pyenv/versions/3.7.2/lib/python3.7/site-packages/aiofiles/threadpool/__init__.py", line 80, in _open
    f = yield from loop.run_in_executor(executor, cb)
  File "/Users/joe/.pyenv/versions/3.7.2/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
FileNotFoundError: [Errno 2] No such file or directory: './static/index.html'

**web response:** 
{"error":"Traceback (most recent call last):\n  File \"\/Users\/joe\/.pyenv\/versions\/3.7.2\/lib\/python3.7\/site-packages\/sanic\/app.py\", line 973, in handle_request\n    response = await response\n  File \".\/index.py\", line 41, in redirect_init\n    return await file(f'{current_dir}\/static\/index.html')\n  File \"\/Users\/joe\/.pyenv\/versions\/3.7.2\/lib\/python3.7\/site-packages\/sanic\/response.py\", line 296, in file\n    async with await open_async(location, mode=\"rb\") as f:\n  File \"\/Users\/joe\/.pyenv\/versions\/3.7.2\/lib\/python3.7\/site-packages\/aiofiles\/base.py\", line 75, in __aenter__\n    self._obj = await self._coro\n  File \"\/Users\/joe\/.pyenv\/versions\/3.7.2\/lib\/python3.7\/site-packages\/aiofiles\/threadpool\/__init__.py\", line 80, in _open\n    f = yield from loop.run_in_executor(executor, cb)\n  File \"\/Users\/joe\/.pyenv\/versions\/3.7.2\/lib\/python3.7\/concurrent\/futures\/thread.py\", line 57, in run\n    result = self.fn(*self.args, **self.kwargs)\nFileNotFoundError: [Errno 2] No such file or directory: '.\/static\/index.html'\n","type":"unexpected"}

**Comment by moshe** [comment]
Hi @joej just fixed the documentation, you can over it here -> https://moshe-1.gitbook.io/comrade/installation/from-source. LMK if it helps

**Comment by moshe** [comment]
Just fixed the documentation, please pull from master and follow the instructions here -> https://moshe-1.gitbook.io/comrade/installation/from-source
Please comment again if still happening
