### ISSUE TITLE
Helm Chart for Elasticsearch-Comrade

### ISSUE THREAD

**Issue by jensjohansen** [moshe/elasticsearch-comrade#905]
We've been looking for a lightweight and recently maintained Elasticsearch GUI that works well for both our developers and our DevOps and ProdOps teams. We want to contribute a helm chart for Comrade unless you already have someone working on one.

**Comment by moshe** [comment]
Hi @jensjohansen, Sounds great! Helm chart contribution sounds like a great idea, thank you in advance 😎
